#define SEGMENT_COUNT 7
#define SEGMENT_SIZE 6

#define TOTAL_NUMBERS_COUNT 4

#define DOT_LED_COUNT 2

#define DIGIT_TOTAL_LEDS SEGMENT_SIZE* SEGMENT_COUNT
#define TOTAL_LED_COUNT DIGIT_TOTAL_LEDS* TOTAL_NUMBERS_COUNT + DOT_LED_COUNT